language: cpp
sudo: required
os:
- linux

compiler:
- g++
#- clang

addons:
    apt:
        sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - cmake
            - ['libqt4-dev', 'libqt4-dbg', 'libqt4-core', 'libqt4-gui']

before_script:
- if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=debug -Dqt5=OFF -Dmetadata=OFF

script:
- make all
- tests/sir_generalgroupbox_test
- make test
