language: cpp
sudo: required
os:
    - linux

compiler:
    - g++

addons:
    apt:
        sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - cmake
            - ['libqt4-dev', 'libqt4-dbg', 'libqtcore4', 'libqtgui4']

before_script:
# set newer GCC version
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
# run virtual screen
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
# setup build
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=debug -Dqt5=OFF -Dmetadata=OFF

script:
    - make all
    - make test
