language: cpp
sudo: required
os:
- linux

compiler:
- gcc
- clang

addons:
    apt:
        sources: ['kalakris-cmake']
        packages: ['cmake']

before_script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=debug

script:
- make all
- make test
