#############################################################################
# Makefile for building: sir
# Generated by qmake (2.01a) (Qt 4.7.4) on: wt. sty 24 14:01:42 2012
# Project:  sir.pro
# Template: app
# Command: /home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile sir.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ -I. -I../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/474/gcc/include/QtNetwork -I../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/474/gcc/include -Isrc -I.moc -I.ui
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/piotrek/QtSDK/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/piotrek/QtSDK/Desktop/Qt/474/gcc/lib -lexiv2 -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/main.cpp \
		src/convertdialog.cpp \
		src/previewdialog.cpp \
		src/optionsdialog.cpp \
		src/myqtreewidget.cpp \
		src/convertthread.cpp \
		src/aboutdialog.cpp \
		src/languageutils.cpp \
		src/sharedinformation.cpp \
		src/rawutils.cpp \
		src/networkutils.cpp \
		src/messagebox.cpp \
		src/metadatautils.cpp \
		src/historycombobox.cpp \
		src/metadata/exif.cpp \
		src/metadatadialog.cpp \
		src/timecombobox.cpp \
		src/metadata/string.cpp \
		src/application.cpp \
		src/metadata/error.cpp .moc/moc_convertdialog.cpp \
		.moc/moc_previewdialog.cpp \
		.moc/moc_optionsdialog.cpp \
		.moc/moc_myqtreewidget.cpp \
		.moc/moc_convertthread.cpp \
		.moc/moc_aboutdialog.cpp \
		.moc/moc_networkutils.cpp \
		.moc/moc_messagebox.cpp \
		.moc/moc_metadatautils.cpp \
		.moc/moc_historycombobox.cpp \
		.moc/moc_metadatadialog.cpp \
		.moc/moc_timecombobox.cpp \
		qrc_application.cpp
OBJECTS       = .obj/main.o \
		.obj/convertdialog.o \
		.obj/previewdialog.o \
		.obj/optionsdialog.o \
		.obj/myqtreewidget.o \
		.obj/convertthread.o \
		.obj/aboutdialog.o \
		.obj/languageutils.o \
		.obj/sharedinformation.o \
		.obj/rawutils.o \
		.obj/networkutils.o \
		.obj/messagebox.o \
		.obj/metadatautils.o \
		.obj/historycombobox.o \
		.obj/exif.o \
		.obj/metadatadialog.o \
		.obj/timecombobox.o \
		.obj/string.o \
		.obj/application.o \
		.obj/error.o \
		.obj/moc_convertdialog.o \
		.obj/moc_previewdialog.o \
		.obj/moc_optionsdialog.o \
		.obj/moc_myqtreewidget.o \
		.obj/moc_convertthread.o \
		.obj/moc_aboutdialog.o \
		.obj/moc_networkutils.o \
		.obj/moc_messagebox.o \
		.obj/moc_metadatautils.o \
		.obj/moc_historycombobox.o \
		.obj/moc_metadatadialog.o \
		.obj/moc_timecombobox.o \
		.obj/qrc_application.o
DIST          = ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		sir.pro
QMAKE_TARGET  = sir
DESTDIR       = 
TARGET        = sir

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .ui/ui_convertdialog.h .ui/ui_about.h .ui/ui_optionsdialog.h .ui/ui_previewdialog.h .ui/ui_metadatadialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sir.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile sir.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile sir.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/sir1.0.0 || $(MKDIR) .obj/sir1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/sir1.0.0/ && $(COPY_FILE) --parents src/main.h src/convertdialog.h src/previewdialog.h src/optionsdialog.h src/myqtreewidget.h src/convertthread.h src/aboutdialog.h src/defines.h src/languageutils.h src/sharedinformation.h src/rawutils.h src/networkutils.h src/messagebox.h src/metadatautils.h src/historycombobox.h src/metadata/exif.h src/metadatadialog.h src/timecombobox.h src/metadata/string.h src/application.h src/metadata/error.h .obj/sir1.0.0/ && $(COPY_FILE) --parents application.qrc .obj/sir1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/convertdialog.cpp src/previewdialog.cpp src/optionsdialog.cpp src/myqtreewidget.cpp src/convertthread.cpp src/aboutdialog.cpp src/languageutils.cpp src/sharedinformation.cpp src/rawutils.cpp src/networkutils.cpp src/messagebox.cpp src/metadatautils.cpp src/historycombobox.cpp src/metadata/exif.cpp src/metadatadialog.cpp src/timecombobox.cpp src/metadata/string.cpp src/application.cpp src/metadata/error.cpp .obj/sir1.0.0/ && $(COPY_FILE) --parents dialogs/convertdialog.ui dialogs/about.ui dialogs/optionsdialog.ui dialogs/previewdialog.ui dialogs/metadatadialog.ui .obj/sir1.0.0/ && $(COPY_FILE) --parents translations/sir_pt_BR.ts translations/sir_de.ts translations/sir_es.ts translations/sir_sk.ts translations/sir_ru_RU.ts translations/sir_hu_HU.ts translations/sir_pl.ts translations/sir_nl.ts translations/sir_ro_RO.ts translations/sir_fr.ts translations/sir_gr.ts translations/sir_cz.ts .obj/sir1.0.0/ && (cd `dirname .obj/sir1.0.0` && $(TAR) sir1.0.0.tar sir1.0.0 && $(COMPRESS) sir1.0.0.tar) && $(MOVE) `dirname .obj/sir1.0.0`/sir1.0.0.tar.gz . && $(DEL_FILE) -r .obj/sir1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_convertdialog.cpp .moc/moc_previewdialog.cpp .moc/moc_optionsdialog.cpp .moc/moc_myqtreewidget.cpp .moc/moc_convertthread.cpp .moc/moc_aboutdialog.cpp .moc/moc_networkutils.cpp .moc/moc_messagebox.cpp .moc/moc_metadatautils.cpp .moc/moc_historycombobox.cpp .moc/moc_metadatadialog.cpp .moc/moc_timecombobox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_convertdialog.cpp .moc/moc_previewdialog.cpp .moc/moc_optionsdialog.cpp .moc/moc_myqtreewidget.cpp .moc/moc_convertthread.cpp .moc/moc_aboutdialog.cpp .moc/moc_networkutils.cpp .moc/moc_messagebox.cpp .moc/moc_metadatautils.cpp .moc/moc_historycombobox.cpp .moc/moc_metadatadialog.cpp .moc/moc_timecombobox.cpp
.moc/moc_convertdialog.cpp: .ui/ui_convertdialog.h \
		src/convertthread.h \
		src/sharedinformation.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/convertdialog.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/convertdialog.h -o .moc/moc_convertdialog.cpp

.moc/moc_previewdialog.cpp: .ui/ui_previewdialog.h \
		src/previewdialog.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/previewdialog.h -o .moc/moc_previewdialog.cpp

.moc/moc_optionsdialog.cpp: .ui/ui_optionsdialog.h \
		src/optionsdialog.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/optionsdialog.h -o .moc/moc_optionsdialog.cpp

.moc/moc_myqtreewidget.cpp: src/myqtreewidget.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/myqtreewidget.h -o .moc/moc_myqtreewidget.cpp

.moc/moc_convertthread.cpp: src/sharedinformation.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/convertthread.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/convertthread.h -o .moc/moc_convertthread.cpp

.moc/moc_aboutdialog.cpp: .ui/ui_about.h \
		src/aboutdialog.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/aboutdialog.h -o .moc/moc_aboutdialog.cpp

.moc/moc_networkutils.cpp: src/networkutils.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/networkutils.h -o .moc/moc_networkutils.cpp

.moc/moc_messagebox.cpp: src/messagebox.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/messagebox.h -o .moc/moc_messagebox.cpp

.moc/moc_metadatautils.cpp: src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/metadatautils.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/metadatautils.h -o .moc/moc_metadatautils.cpp

.moc/moc_historycombobox.cpp: src/historycombobox.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/historycombobox.h -o .moc/moc_historycombobox.cpp

.moc/moc_metadatadialog.cpp: .ui/ui_metadatadialog.h \
		src/metadatadialog.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/metadatadialog.h -o .moc/moc_metadatadialog.cpp

.moc/moc_timecombobox.cpp: src/timecombobox.h
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) src/timecombobox.h -o .moc/moc_timecombobox.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		translations/sir_ru_RU.qm \
		translations/sir_cz.qm \
		translations/sir_hu_HU.qm \
		translations/sir_de.qm \
		translations/sir_es.qm \
		translations/sir_nl.qm \
		translations/sir_ro_RO.qm \
		translations/sir_sk.qm \
		translations/sir_fr.qm \
		translations/sir_gr.qm \
		translations/sir_pl.qm \
		translations/translation_info.txt \
		translations/sir_pt_BR.qm \
		images/zoom.png \
		images/print.png \
		images/sir-64x64.png \
		images/polish.png \
		images/rotate_ccw.png \
		images/czech.png \
		images/flip_vertical.png \
		images/filesave.png \
		images/spanish.png \
		images/french.png \
		images/sir-32x32.png \
		images/german.png \
		images/dutch.png \
		images/russian.png \
		images/flip_horizontal.png \
		images/options_metadata.png \
		images/next.png \
		images/unfavorite.png \
		images/options_raw.png \
		images/window_fullscreen.png \
		images/portuguese.png \
		images/filesaveas.png \
		images/rotate_cw.png \
		images/hungarian.png \
		images/romanian.png \
		images/exit.png \
		images/previous.png \
		images/options_general.png \
		images/english.png \
		images/favorite.png \
		images/greek.png \
		images/slovak.png
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: .ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .ui/ui_convertdialog.h .ui/ui_about.h .ui/ui_optionsdialog.h .ui/ui_previewdialog.h .ui/ui_metadatadialog.h
compiler_uic_clean:
	-$(DEL_FILE) .ui/ui_convertdialog.h .ui/ui_about.h .ui/ui_optionsdialog.h .ui/ui_previewdialog.h .ui/ui_metadatadialog.h
.ui/ui_convertdialog.h: dialogs/convertdialog.ui
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/uic dialogs/convertdialog.ui -o .ui/ui_convertdialog.h

.ui/ui_about.h: dialogs/about.ui
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/uic dialogs/about.ui -o .ui/ui_about.h

.ui/ui_optionsdialog.h: dialogs/optionsdialog.ui
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/uic dialogs/optionsdialog.ui -o .ui/ui_optionsdialog.h

.ui/ui_previewdialog.h: dialogs/previewdialog.ui
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/uic dialogs/previewdialog.ui -o .ui/ui_previewdialog.h

.ui/ui_metadatadialog.h: dialogs/metadatadialog.ui
	/home/piotrek/QtSDK/Desktop/Qt/474/gcc/bin/uic dialogs/metadatadialog.ui -o .ui/ui_metadatadialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

.obj/main.o: src/main.cpp src/main.h \
		src/convertdialog.h \
		.ui/ui_convertdialog.h \
		src/convertthread.h \
		src/sharedinformation.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/convertdialog.o: src/convertdialog.cpp src/convertdialog.h \
		.ui/ui_convertdialog.h \
		src/convertthread.h \
		src/sharedinformation.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/previewdialog.h \
		.ui/ui_previewdialog.h \
		src/myqtreewidget.h \
		src/aboutdialog.h \
		.ui/ui_about.h \
		src/optionsdialog.h \
		.ui/ui_optionsdialog.h \
		src/defines.h \
		src/rawutils.h \
		src/networkutils.h \
		src/messagebox.h \
		src/metadatadialog.h \
		.ui/ui_metadatadialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/convertdialog.o src/convertdialog.cpp

.obj/previewdialog.o: src/previewdialog.cpp src/previewdialog.h \
		.ui/ui_previewdialog.h \
		src/rawutils.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/previewdialog.o src/previewdialog.cpp

.obj/optionsdialog.o: src/optionsdialog.cpp src/optionsdialog.h \
		.ui/ui_optionsdialog.h \
		src/languageutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/optionsdialog.o src/optionsdialog.cpp

.obj/myqtreewidget.o: src/myqtreewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/myqtreewidget.o src/myqtreewidget.cpp

.obj/convertthread.o: src/convertthread.cpp src/convertthread.h \
		src/sharedinformation.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/defines.h \
		src/rawutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/convertthread.o src/convertthread.cpp

.obj/aboutdialog.o: src/aboutdialog.cpp src/aboutdialog.h \
		.ui/ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/aboutdialog.o src/aboutdialog.cpp

.obj/languageutils.o: src/languageutils.cpp src/languageutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/languageutils.o src/languageutils.cpp

.obj/sharedinformation.o: src/sharedinformation.cpp src/sharedinformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/sharedinformation.o src/sharedinformation.cpp

.obj/rawutils.o: src/rawutils.cpp src/rawutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/rawutils.o src/rawutils.cpp

.obj/networkutils.o: src/networkutils.cpp src/networkutils.h \
		src/defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/networkutils.o src/networkutils.cpp

.obj/messagebox.o: src/messagebox.cpp src/messagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/messagebox.o src/messagebox.cpp

.obj/metadatautils.o: src/metadatautils.cpp src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h \
		src/defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/metadatautils.o src/metadatautils.cpp

.obj/historycombobox.o: src/historycombobox.cpp src/historycombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/historycombobox.o src/historycombobox.cpp

.obj/exif.o: src/metadata/exif.cpp src/metadata/exif.h \
		src/metadata/string.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/exif.o src/metadata/exif.cpp

.obj/metadatadialog.o: src/metadatadialog.cpp src/metadatadialog.h \
		.ui/ui_metadatadialog.h \
		src/metadatautils.h \
		src/metadata/exif.h \
		src/metadata/string.h \
		src/metadata/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/metadatadialog.o src/metadatadialog.cpp

.obj/timecombobox.o: src/timecombobox.cpp src/timecombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/timecombobox.o src/timecombobox.cpp

.obj/string.o: src/metadata/string.cpp src/metadata/string.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/string.o src/metadata/string.cpp

.obj/application.o: src/application.cpp src/application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/application.o src/application.cpp

.obj/error.o: src/metadata/error.cpp src/metadata/error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/error.o src/metadata/error.cpp

.obj/moc_convertdialog.o: .moc/moc_convertdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_convertdialog.o .moc/moc_convertdialog.cpp

.obj/moc_previewdialog.o: .moc/moc_previewdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_previewdialog.o .moc/moc_previewdialog.cpp

.obj/moc_optionsdialog.o: .moc/moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_optionsdialog.o .moc/moc_optionsdialog.cpp

.obj/moc_myqtreewidget.o: .moc/moc_myqtreewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_myqtreewidget.o .moc/moc_myqtreewidget.cpp

.obj/moc_convertthread.o: .moc/moc_convertthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_convertthread.o .moc/moc_convertthread.cpp

.obj/moc_aboutdialog.o: .moc/moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_aboutdialog.o .moc/moc_aboutdialog.cpp

.obj/moc_networkutils.o: .moc/moc_networkutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_networkutils.o .moc/moc_networkutils.cpp

.obj/moc_messagebox.o: .moc/moc_messagebox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_messagebox.o .moc/moc_messagebox.cpp

.obj/moc_metadatautils.o: .moc/moc_metadatautils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_metadatautils.o .moc/moc_metadatautils.cpp

.obj/moc_historycombobox.o: .moc/moc_historycombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_historycombobox.o .moc/moc_historycombobox.cpp

.obj/moc_metadatadialog.o: .moc/moc_metadatadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_metadatadialog.o .moc/moc_metadatadialog.cpp

.obj/moc_timecombobox.o: .moc/moc_timecombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_timecombobox.o .moc/moc_timecombobox.cpp

.obj/qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_application.o qrc_application.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_images: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/images/sir-128x128.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/images/sir-32x32.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/images/sir-64x64.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/images/sir.ico $(INSTALL_ROOT)/usr/share/pixmaps/
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/images/sir.png $(INSTALL_ROOT)/usr/share/pixmaps/


uninstall_images:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/sir-128x128.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/sir-32x32.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/sir-64x64.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/sir.ico 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/sir.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/sir.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/sir.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_service: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/kde4/services/ServiceMenus/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/kde4/services/ServiceMenus/ 
	-$(INSTALL_FILE) /home/piotrek/Pulpit/projekt/sir_service.desktop $(INSTALL_ROOT)/usr/share/kde4/services/ServiceMenus/


uninstall_service:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/kde4/services/ServiceMenus/sir_service.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/kde4/services/ServiceMenus/ 


install:  install_target install_images install_desktop install_service  FORCE

uninstall: uninstall_target uninstall_images uninstall_desktop uninstall_service   FORCE

FORCE:

